import { PresetArchetype, UserProfile } from './types';

export const DEFAULT_PROFILE: UserProfile = {
  // Demographics & Genetics
  age: 38,
  sex: 'male',
  relationshipStatus: 'partnered_married',
  earlyFamilyDisease: 'none',
  familyLongevity: 'average',
  airQuality: 'moderate_suburban',

  // Biometrics & Clinical
  systolicBP: 124,
  diastolicBP: 82,
  bloodSugar: 'normal',
  lipidStatus: 'moderate_high',
  bmi: 26.2,
  restingHeartRate: 72,

  // Fitness & Movement
  cardio: 'light',
  strengthTraining: 'occasional',
  dailySteps: '4k_to_7k',
  sittingHours: '4h_to_8h',

  // Nutrition & Blue Zone Diet
  dietPattern: 'moderate_balanced',
  redMeat: 'weekly_moderate',
  veggieFruitServings: '2_to_4',
  ultraProcessed: 'occasional',
  polyphenols: 'moderate_coffee_tea',
  dailyWaterGlasses: 6,

  // Lifestyle, Sleep & Mind
  smoking: 'never',
  alcohol: 'light_moderate',
  sleep: '6_to_7h',
  stress: 'moderate_daily',
  socialConnection: 'moderate',
  intimacyFrequency: 'monthly_occasional',
  flossing: 'occasional',
  sunProtection: true,
  seatbeltSafety: true,
  screenings: 'up_to_date',
};

export const PRESET_ARCHETYPES: PresetArchetype[] = [
  {
    id: 'average_us',
    name: 'Average Modern Adult',
    shortDesc: 'Typical baseline with desk job, moderate exercise, occasional fast food, and mild stress.',
    icon: '👤',
    profile: { ...DEFAULT_PROFILE },
  },
  {
    id: 'bluezone_centenarian',
    name: 'Blue Zone Centenarian',
    shortDesc: 'Okinawa/Sardinia lifestyle: plant-rich diet, deep community (Moai), daily walking, zero smoking, and low stress.',
    icon: '🌿',
    profile: {
      age: 40,
      sex: 'female',
      relationshipStatus: 'partnered_married',
      earlyFamilyDisease: 'none',
      familyLongevity: 'centenarian_100plus',
      airQuality: 'clean_rural',
      systolicBP: 112,
      diastolicBP: 74,
      bloodSugar: 'normal',
      lipidStatus: 'optimal',
      bmi: 21.8,
      restingHeartRate: 58,
      cardio: 'high',
      strengthTraining: 'optimal',
      dailySteps: 'over_10k',
      sittingHours: 'under_4h',
      dietPattern: 'mediterranean_bluezone',
      redMeat: 'rare_none',
      veggieFruitServings: '5_plus',
      ultraProcessed: 'minimal_rare',
      polyphenols: 'high_green_tea_berries',
      dailyWaterGlasses: 8,
      smoking: 'never',
      alcohol: 'light_moderate',
      sleep: '7_to_8h_optimal',
      stress: 'well_managed_mindful',
      socialConnection: 'strong_connected',
      intimacyFrequency: 'weekly_optimal',
      flossing: 'daily_flossing',
      sunProtection: true,
      seatbeltSafety: true,
      screenings: 'up_to_date',
    },
  },
  {
    id: 'biohacker_optimal',
    name: 'Longevity Enthusiast & Athlete',
    shortDesc: 'Maximized VO2 max, 3x strength training, optimal biomarker control, strict sleep protocol, and daily flossing.',
    icon: '⚡',
    profile: {
      age: 35,
      sex: 'male',
      relationshipStatus: 'partnered_married',
      earlyFamilyDisease: 'none',
      familyLongevity: 'relative_90_99',
      airQuality: 'clean_rural',
      systolicBP: 115,
      diastolicBP: 75,
      bloodSugar: 'normal',
      lipidStatus: 'optimal',
      bmi: 23.0,
      restingHeartRate: 52,
      cardio: 'high',
      strengthTraining: 'optimal',
      dailySteps: 'over_10k',
      sittingHours: 'under_4h',
      dietPattern: 'mediterranean_bluezone',
      redMeat: 'rare_none',
      veggieFruitServings: '5_plus',
      ultraProcessed: 'minimal_rare',
      polyphenols: 'high_green_tea_berries',
      dailyWaterGlasses: 10,
      smoking: 'never',
      alcohol: 'none',
      sleep: '7_to_8h_optimal',
      stress: 'well_managed_mindful',
      socialConnection: 'strong_connected',
      intimacyFrequency: 'weekly_optimal',
      flossing: 'daily_flossing',
      sunProtection: true,
      seatbeltSafety: true,
      screenings: 'up_to_date',
    },
  },
  {
    id: 'stressed_workaholic',
    name: 'Stressed Desk Professional',
    shortDesc: '8+ hours sitting, high chronic work stress, fast food, sleep deprivation, Stage 1 BP, and neglected screenings.',
    icon: '💼',
    profile: {
      age: 42,
      sex: 'male',
      relationshipStatus: 'single',
      earlyFamilyDisease: 'early_cvd',
      familyLongevity: 'average',
      airQuality: 'polluted_urban',
      systolicBP: 138,
      diastolicBP: 88,
      bloodSugar: 'prediabetes',
      lipidStatus: 'high_uncontrolled',
      bmi: 29.5,
      restingHeartRate: 84,
      cardio: 'sedentary',
      strengthTraining: 'none',
      dailySteps: 'under_4k',
      sittingHours: 'over_8h',
      dietPattern: 'standard_processed',
      redMeat: 'frequent_daily',
      veggieFruitServings: 'under_2',
      ultraProcessed: 'daily_frequent',
      polyphenols: 'moderate_coffee_tea',
      dailyWaterGlasses: 3,
      smoking: 'never',
      alcohol: 'heavy_binge',
      sleep: 'under_6h',
      stress: 'severe_unmanaged',
      socialConnection: 'isolated',
      intimacyFrequency: 'rare_none',
      flossing: 'rarely_never',
      sunProtection: false,
      seatbeltSafety: true,
      screenings: 'neglected',
    },
  },
  {
    id: 'heavy_smoker',
    name: 'Sedentary Heavy Smoker',
    shortDesc: '1+ pack/day smoking, physical inactivity, high blood pressure, and low dietary antioxidant intake.',
    icon: '🚬',
    profile: {
      age: 45,
      sex: 'male',
      relationshipStatus: 'separated_divorced_widowed',
      earlyFamilyDisease: 'multiple_early',
      familyLongevity: 'average',
      airQuality: 'polluted_urban',
      systolicBP: 148,
      diastolicBP: 94,
      bloodSugar: 'type2_controlled',
      lipidStatus: 'high_uncontrolled',
      bmi: 31.2,
      restingHeartRate: 88,
      cardio: 'sedentary',
      strengthTraining: 'none',
      dailySteps: 'under_4k',
      sittingHours: 'over_8h',
      dietPattern: 'standard_processed',
      redMeat: 'frequent_daily',
      veggieFruitServings: 'under_2',
      ultraProcessed: 'daily_frequent',
      polyphenols: 'none',
      dailyWaterGlasses: 3,
      smoking: 'current_heavy',
      alcohol: 'heavy_binge',
      sleep: 'under_6h',
      stress: 'severe_unmanaged',
      socialConnection: 'isolated',
      intimacyFrequency: 'rare_none',
      flossing: 'rarely_never',
      sunProtection: false,
      seatbeltSafety: false,
      screenings: 'neglected',
    },
  },
];
